export const products = {
  "pe-pipe-extrusion-line": {
    title: "PE Pipe Extrusion Line",
    description:
      "PE pipe extrusion machine for Ø 16-2000mm water, gas, drainage, conduit, PP, PPR, PERT, PB and PEX-B pipe production.",
    paragraphs: [
      "Our PE pipe extrusion machine can produce PE size range from Ø 16 to Ø 2000mm.",
      "PE pipes can be used for water supply, gas supply, water drainage, liquid transportation, electric conduit, etc.",
      "Our PE pipe extrusion machine can process different kinds of PO materials: PP, PPR, PERT, PB, PEX-B, etc.",
      "We can provide different PE pipe extrusion lines: normal or high speed, single or multi-layer, single or double strand.",
      "In addition, we can provide turnkey solution with auxiliary machinery such as mixer, shredder, crusher etc.",
    ],
    images: [
      "/images/products/pe-pipe-extrusion-line/pe-pipe-extrusion-line-hero.jpg",
      "/images/products/pe-pipe-extrusion-line/pe-pipe-extrusion-machine-overview.jpg",
      "/images/products/pe-pipe-extrusion-line/pe-pipe-extrusion-line-extruder-unit.jpg",
      "/images/products/pe-pipe-extrusion-line/pe-pipe-extrusion-die-head-system.jpg",
      "/images/products/pe-pipe-extrusion-line/pe-pipe-extrusion-vacuum-calibration-tank.jpg",
      "/images/products/pe-pipe-extrusion-line/pe-pipe-extrusion-haul-off-machine.jpg",
      "/images/products/pe-pipe-extrusion-line/pe-pipe-extrusion-cutter-unit.jpg",
      "/images/products/pe-pipe-extrusion-line/pe-pipe-extrusion-control-panel-plc.jpg",
      "/images/products/pe-pipe-extrusion-line/pe-pipe-extrusion-production-line-overview.jpg",
    ],
    videoId: "VIFfEr4YWlI?start=54",
    features: [
      "Whole extrusion line adopts touch screen and PLC control, linked to achieve high degree of automation.",
      "Screw with L/D ratio 38:1 or 40:1, can realize high output extrusion with low melt temperature and low power consumption.",
      "Die head with core cooling, also with air cooling inside pipe, to have good pipe forming.",
      "Vacuum tank can be equipped with automatic vacuum degree control system, to realize automatic water level and vacuum degree control, also reduce power consumption in long run.",
      "Gravimetric dosing system is for choice, it can make operation easier, control pipe wall thickness and meter weight accurately, also can show the power consumption per unit weight for the pipe.",
      "By changing some parts, extrusion line can also produce other PO pipes, such as PP, PPR, PERT, PB, PEX-B, etc.",
      "By changing some parts, extrusion line can produce single layer or multi-layer, single strand and double strand pipe.",
    ],
    specHeaders: ["Model", "Pipe Range (mm)", "Output Capacity (kg/h)", "Main Motor Power (kW)"],
    specs: [
      ["PE63", "16 - 63", "150 - 300", "45 - 75"],
      ["PE110", "20 - 110", "220 - 360", "55 - 90"],
      ["PE160", "50 - 160", "300 - 440", "75 - 110"],
      ["PE250", "75 - 250", "360 - 500", "90 - 132"],
      ["PE315", "90 - 315", "440 - 640", "110 - 160"],
      ["PE450", "110 - 450", "500 - 800", "132 - 200"],
      ["PE630", "250 - 630", "640 - 1000", "160 - 250"],
      ["PE800", "315 - 800", "800 - 1200", "200 - 355"],
      ["PE1000", "400 - 1000", "1000 - 1500", "250 - 355"],
      ["PE1200", "500 - 1200", "1200 - 1800", "355 - (250x2)"],
      ["PE1600", "710 - 1600", "1800 - 2400", "(250x2) - (355x2)"],
      ["PE2000", "800 - 2000", "2400 - 3000", "(355x2) - (400x2)"],
    ],
  },
  "pvc-pipe-extrusion-line": {
    title: "PVC Pipe Extrusion Line",
    description:
      "PVC pipe extrusion machine for Ø 16-1000mm UPVC, CPVC, PVC-O and PVC-M pipe production.",
    paragraphs: [
      "Our PVC pipe extrusion machine can produce PVC pipe size range from Ø 16 to Ø 1000mm.",
      "PVC pipes can be used for water supply, water drainage, liquid transportation, electric conduit, etc.",
      "We have different kinds of PVC pipe making machine to produce different kinds of PVC pipes: UPVC pipe, CPVC pipe, PVC-O pipe, PVC-M pipe, etc.",
      "We can provide different PVC pipe extrusion lines: normal or high speed, single or multi-layer, single or double strand.",
      "In addition, we can provide turnkey solution with auxiliary machinery such as mixer, shredder, crusher and pulverizer, etc.",
    ],
    images: [
      "/images/products/pvc-pipe-extrusion-line/pvc-pipe-extrusion-line-hero.jpg",
      "/images/products/pvc-pipe-extrusion-line/pvc-pipe-extrusion-machine-overview.jpg",
      "/images/products/pvc-pipe-extrusion-line/pvc-pipe-extrusion-twin-screw-extruder.jpg",
      "/images/products/pvc-pipe-extrusion-line/pvc-pipe-extrusion-vacuum-tank.jpg",
      "/images/products/pvc-pipe-extrusion-line/pvc-pipe-extrusion-haul-off-cutter.jpg",
      "/images/products/pvc-pipe-extrusion-line/pvc-pipe-extrusion-control-system.jpg",
      "/images/products/pvc-pipe-extrusion-line/pvc-pvc-pipe-production-line.jpg",
    ],
    videoId: "_UxwY8U5hys",
    features: [
      "Conical twin screw and parallel twin screw (28:1, 36:1) extruders are for choice.",
      "Vacuum tank can be equipped with automatic vacuum degree control system, to realize automatic water level and vacuum degree control, also reduce power consumption in long run.",
      "Swarfless knife cutter and planetary saw cutter are for choice, both cutters are with chamfering function.",
      "Weightless feeding system is for choice, it can make operation easier, control pipe wall thickness and meter weight accurately, also can show the power consumption per unit weight for the pipe.",
      "By changing some parts, extrusion line can also produce CPVC pipe, PVC-O pipe, PVC-M pipe, etc.",
      "By changing some parts, extrusion line can produce single layer or multi-layer, single strand and double strand pipe.",
    ],
    specHeaders: ["Model", "Pipe Range (mm)", "Output Capacity (kg/h)", "Main Motor Power (kW)"],
    specs: [
      ["PVC32SS*", "(Ø16 - 32) x 4", "180 - 250", "22 - 37"],
      ["PVC63", "Ø16 - 63", "180 - 250", "22 - 37"],
      ["PVC63S*", "(Ø16 - 63) x 2", "250 - 450", "37 - 55"],
      ["PVC110", "Ø20 - 110", "250 - 450", "37 - 55"],
      ["PVC160", "Ø50 - 160", "250 - 450", "37 - 55"],
      ["PVC250", "Ø75 - 250", "450 - 750", "55 - 75"],
      ["PVC450", "Ø110 - 450", "450 - 1000", "55 - 110"],
      ["PVC630", "Ø250 - 630", "800 - 1200", "110 - 132"],
      ["PVC800", "Ø315 - 800", "1200 - 1300", "132 - 160"],
      ["PVC1000", "Ø400 - 1000", "1300", "160"],
    ],
  },
  "pvc-o-pipe-extrusion-line": {
    title: "PVC-O Pipe Extrusion Line",
    description:
      "PVC-O pipe extrusion machine for Ø 90-630mm, PN5-25 and material class 315-500.",
    paragraphs: [
      "Our PVC-O pipe extrusion machine can produce PVC-O pipe size range from Ø90 to Ø630mm for PN5 to 25, and Material Class 315 to 500.",
      "PVC-O pipe, biaxially oriented polyvinyl chloride pipe, can be used for water supply, mining, gas supply, etc.",
      "We use one step forming method to produce PVC-O pipe which has advantage of less space, low electricity and labour cost, less material waste.",
      "We can provide turnkey solution with auxiliary machinery such as mixer, shredder, crusher and pulverizer, etc.",
    ],
    images: [
      "/images/products/pvc-o-pipe-extrusion-line/pvc-o-pipe-extrusion-line-hero.jpg",
      "/images/products/pvc-o-pipe-extrusion-line/pvc-o-pipe-extrusion-machine-overview.jpg",
      "/images/products/pvc-o-pipe-extrusion-line/pvc-o-pipe-extrusion-line-setup.jpg",
      "/images/products/pvc-o-pipe-extrusion-line/pvc-o-pipe-biaxial-orientation-production.jpg",
    ],
    videoId: "YWr8hySZqqw",
    features: [
      "This is another equipment independently developed by our company for 8 years.",
      "Real-time feedback of important data on pipe production makes it easy to adjust pipe production process.",
      "With complete process storage function to facilitate future pipe production.",
      "The entire line is highly automated, and the wall thickness is automatically adjusted through gravimetric dosing system and PLC to reduce material waste.",
      "Equipped with a remote diagnosis system. When problems occur, we will provide customers with quick guidance and troubleshooting services based on the equipment operating parameters.",
    ],
    specHeaders: ["Model", "Pipe Range (mm)", "Material Class/MRS (max)", "Main Motor Power (kW)"],
    specs: [
      ["PVC-O160", "90 - 160", "500", "37"],
      ["PVC-O200", "110 - 200", "500", "45"],
      ["PVC-O400", "200 - 400", "500", "75"],
      ["PVC-O500", "250 - 500", "500", "90"],
      ["PVC-O630", "315 - 630", "500", "110"],
    ],
  },
  "ppr-pipe-extrusion-line": {
    title: "PPR Pipe Extrusion Line",
    description: "PPR pipe machine for Ø 16-160mm cold and hot water supply pipe production.",
    paragraphs: [
      "Our PPR pipe machine can produce PPR size range from 16 to 160mm. However, our machine can produce bigger size if required.",
      "PPR pipe is mainly used for cold water and hot water supply.",
      "With additional extruder and changing die head structure, the machine can also produce PPR fiberglass composite pipe.",
      "We can provide different PPR pipe extrusion lines: normal or high speed, single or multi-layer, single or double strand.",
    ],
    images: [
      "/images/products/ppr-pipe-extrusion-line/ppr-pipe-extrusion-line-hero.jpg",
      "/images/products/ppr-pipe-extrusion-line/ppr-pipe-extrusion-machine-overview.jpg",
      "/images/products/ppr-pipe-extrusion-line/ppr-pipe-extrusion-line-extruder-unit.jpg",
      "/images/products/ppr-pipe-extrusion-line/ppr-pipe-extrusion-die-head-system.jpg",
      "/images/products/ppr-pipe-extrusion-line/ppr-pipe-extrusion-vacuum-calibration-tank.jpg",
      "/images/products/ppr-pipe-extrusion-line/ppr-pipe-extrusion-haul-off-machine.jpg",
      "/images/products/ppr-pipe-extrusion-line/ppr-pipe-extrusion-cutter-unit.jpg",
    ],
    videoId: "mQk-puCkzbQ",
    features: [
      "Whole extrusion line adopts touch screen and PLC control, linked to achieve high degree of automation.",
      "Screw with L/D ratio 38:1 or 40:1, can realize high output extrusion with low melt temperature and low power consumption.",
      "Vacuum tank can be equipped with automatic vacuum degree control system, to realize automatic water level and vacuum degree control, also reduce power consumption in long run.",
      "Gravimetric dosing system is for choice, it can make operation easier, control pipe wall thickness and meter weight accurately, also can show the power consumption per unit weight for the pipe.",
    ],
    specHeaders: ["Model", "Pipe Range (mm)", "Output Capacity (kg/h)", "Main Motor Power (kW)"],
    specs: [
      ["PPR63", "16 - 63", "150 - 260", "45 - 75"],
      ["PPR63S*", "(16 - 63) x 2", "260 - 450", "75 - 132"],
      ["PPR110", "20 - 110", "190 - 320", "55 - 90"],
      ["PPR160", "50 - 160", "260 - 400", "75 - 110"],
    ],
  },
  "double-wall-corrugated-pipe-extrusion-line": {
    title: "Double Wall Corrugated Pipe Extrusion Line",
    description: "Double wall corrugated pipe extrusion machine for Ø 63-1200mm drainage and ventilation pipe.",
    paragraphs: [
      "Our double wall corrugated pipe extrusion machine can produce pipe size range from Ø63-1200mm.",
      "Double wall corrugated pipe is mainly used for water drainage and ventilation.",
      "Usually, double wall corrugated pipe is PE material. But changing extruder type can produce PVC double wall corrugated pipe.",
      "We have two different types of corrugated pipe machine for your choice: horizontal type and vertical type.",
    ],
    images: [
      "/images/products/double-wall-corrugated-pipe-extrusion-line/double-wall-corrugated-pipe-extrusion-line-hero.jpg",
      "/images/products/double-wall-corrugated-pipe-extrusion-line/double-wall-corrugated-pipe-extrusion-machine-overview.jpg",
      "/images/products/double-wall-corrugated-pipe-extrusion-line/double-wall-corrugated-pipe-corrugator-molding-unit.jpg",
      "/images/products/double-wall-corrugated-pipe-extrusion-line/double-wall-corrugated-pipe-cooling-system.jpg",
      "/images/products/double-wall-corrugated-pipe-extrusion-line/double-wall-corrugated-pipe-cutting-system.jpg",
      "/images/products/double-wall-corrugated-pipe-extrusion-line/double-wall-corrugated-pipe-belling-machine.jpg",
      "/images/products/double-wall-corrugated-pipe-extrusion-line/double-wall-corrugated-pipe-production-line.jpg",
    ],
    videoId: "UfOqUDsVNMI",
    features: [
      "Whole production line is centralized to be controlled by touch screen and PLC control system.",
      "Horizontal and closed loop pressure water cooling corrugator structure is for choice.",
      "Machine can produce bigger pipe size range by optimized structure.",
      "Efficient vacuum system and low power consumption.",
      "With automatic on-line belling system.",
      "With automatic and accurate pipe cutting system.",
      "With pipe weighing system.",
    ],
    specHeaders: ["Model", "Pipe Range (mm)", "Corrugator Type", "Output Capacity (kg/h)", "Main Motor Power (kW)"],
    specs: [
      ["WPE160", "63 - 160", "Horizontal", "400", "55+45"],
      ["WPE250", "75 - 250", "Horizontal", "400 - 520", "(55+45) - (75+55)"],
      ["WPE400", "200 - 400", "Horizontal", "740 - 1080", "(110+75) - (160+110)"],
      ["WPE600", "200 - 600", "Vertical", "1080 - 1440", "(160+110) - (200+160)"],
      ["WPE800", "200 - 800", "Vertical", "1520 - 1850", "(220+160) - (280+200)"],
      ["WPE1200", "400 - 1200", "Vertical", "1850 - 2300", "(280+200) - (355+280)"],
    ],
  },
  "pe-hollow-wall-winding-pipe-extrusion-line": {
    title: "PE Hollow Wall Winding Pipe Extrusion Line",
    description: "PE hollow wall winding pipe extrusion machine for Ø 200-3000mm drainage pipe production.",
    paragraphs: [
      "Our PE hollow wall winding pipe extrusion machine can produce pipe size range from Ø200-3000mm.",
      "We are one of the drafters of nation standard for hollow wall winding pipe.",
      "PE hollow wall winding pipe is mainly used for water drainage, same as double wall corrugated pipe.",
      "Compared with double wall corrugated pipe, it has advantages of low machine investment cost and larger pipe diameter.",
      "With different design of profile tube our machinery can produce pipes of different ring stiffness that adapt to different conditions and fields.",
    ],
    images: [
      "/images/products/pe-hollow-wall-winding-pipe-extrusion-line/pe-hollow-wall-winding-pipe-extrusion-line-hero.jpg",
      "/images/products/pe-hollow-wall-winding-pipe-extrusion-line/pe-hollow-wall-winding-pipe-extrusion-machine.jpg",
      "/images/products/pe-hollow-wall-winding-pipe-extrusion-line/pe-hollow-wall-winding-pipe-profile-forming.jpg",
      "/images/products/pe-hollow-wall-winding-pipe-extrusion-line/pe-hollow-wall-winding-pipe-extruder-system.jpg",
      "/images/products/pe-hollow-wall-winding-pipe-extrusion-line/pe-hollow-wall-winding-pipe-production-line.jpg",
      "/images/products/pe-hollow-wall-winding-pipe-extrusion-line/pe-hollow-wall-winding-pipe-welding-unit.jpg",
    ],
    videoId: "coM6iNRuA48",
    features: [
      "Whole line is controlled by PLC, operation is easy and stable.",
      "Adopt unique forming method, the square tube size meets the requirements.",
      "Can work together with socket and spigot injection machine for easy pipe connection.",
      "By changing some parts, extrusion line can also produce multi-layer and wind pipes with different wall structure.",
    ],
    specHeaders: ["Model", "Pipe Range (mm)", "Output Capacity (kg/h)", "Main Motor Power (kW)"],
    specs: [
      ["XCR500", "200 - 500", "450 - 500", "110+22"],
      ["XCR800", "200 - 800", "250 - 500", "(55+15) - (110+22)"],
      ["XCR1200", "300 - 1200", "450 - 500", "110+22"],
      ["XCR1600", "500 - 1600", "900 - 1000", "185+55"],
      ["XCR2400", "1000 - 2400", "1300 - 1400", "315+90"],
      ["XCR3200", "1600 - 3200", "1600 - 1800", "355+110"],
    ],
  },
  "pex-al-pex-pipe-machine": {
    title: "PEX-AL-PEX Pipe Machine",
    description: "PEX-AL-PEX composite pipe extrusion line for Ø 16-63mm five-layer pipe production.",
    paragraphs: [
      "Our PEX-AL-PEX composite pipe extrusion line produce pipe size range from Ø16-63mm.",
      "This pipe is five layer structure: plastic layer, adhesive layer, aluminum layer, adhesive layer and plastic layer.",
      "The aluminum layer is formed by ultrasonic overlap welding.",
      "Our machine can form five layer in one step, to save machine space and increase stability. Production yield can reach 98%, and line speed is also higher.",
      "Pipe made by one step has higher quality, as all material are extruded and integrated at one time, no need to reheat material again.",
    ],
    images: [
      "/images/products/pex-al-pex-pipe-machine/pex-al-pex-pipe-machine-hero.jpg",
      "/images/products/pex-al-pex-pipe-machine/pex-al-pex-pipe-production-line-overview.jpg",
      "/images/products/pex-al-pex-pipe-machine/pex-al-pex-five-layer-pipe-forming.jpg",
      "/images/products/pex-al-pex-pipe-machine/pex-al-pex-aluminum-welding-machine.jpg",
      "/images/products/pex-al-pex-pipe-machine/pex-al-pex-composite-pipe-extrusion.jpg",
      "/images/products/pex-al-pex-pipe-machine/pex-al-pex-pipe-haul-off-unit.jpg",
      "/images/products/pex-al-pex-pipe-machine/pex-al-pex-pipe-control-panel.jpg",
    ],
    videoId: "46uHBXxbEZc",
    features: [
      "Whole line is controlled by PLC, operation is easy and stable.",
      "Five-layer forming in one step, with higher production speed and yield, pipe quality is good.",
      "Ultrasonic welding machine are imported from US, with welding with higher speed and good quality.",
      "Key parts are imported, main parts are manufactured locally which ensures low machine cost.",
    ],
    specHeaders: ["Model", "Pipe Diameter Range (mm)", "Line Speed (m/min)", "Total Power (kW)"],
    specs: [
      ["XRL32", "16 - 32", "7 - 15", "90"],
      ["XRL63", "16 - 63", "2 - 15", "120"],
    ],
  },
  "rtp-tcp-pipe-production-line": {
    title: "RTP/TCP Pipe Production Line",
    description: "RTP/TCP pipe production line for Ø 50-630mm high-pressure reinforced thermoplastic pipe.",
    paragraphs: [
      "Our RTP/TCP pipe production line can produce pipe size range from Ø50-630mm.",
      "The RTP, thermoplastic reinforced pipe, and TCP, thermoplastic composite pipe, are mainly used as high pressure and non-metallic pipes for oil and gas industries.",
      "They can also be used for water supply and district heating.",
      "Compared with other kinds of high pressure pipes, RTP/TCP has advantage of easy installation and connection, more flexibility, long service life, low cost and reliability.",
      "By changing the inner layer material, the RTP/TCP pipe can work under different temperature and circumstance.",
    ],
    images: [
      "/images/products/rtp-tcp-pipe-production-line/rtp-tcp-pipe-production-line-hero.jpg",
      "/images/products/rtp-tcp-pipe-production-line/rtp-tcp-pipe-winding-machine-overview.jpg",
      "/images/products/rtp-tcp-pipe-production-line/rtp-tcp-pipe-reinforced-tape-winding-process.jpg",
      "/images/products/rtp-tcp-pipe-production-line/rtp-tcp-pipe-production-line-setup.jpg",
      "/images/products/rtp-tcp-pipe-production-line/rtp-tcp-pipe-control-system.jpg",
    ],
    videoId: "7KeAQEZ_Ads",
    features: [
      "The full PLC control allows the production line to have a high level of automation and winding efficiency.",
      "Adopt automatic winding process, and evenly wrap the pipe with reinforced tape through the winding machines.",
      "Winding machine adopts servo drives for accurate layering and winding control.",
      "The rotation speed of the winding machine can be automatically adjusted according to the production line speed to ensure that the winding angle meets the requirements.",
      "Close loop control system to ensure accurate, stable and constant tape tension control.",
      "According to different types of reinforced tape and different pipeline pressure requirements, we will equip different quantities of winding machines.",
      "The reinforced tape can be in different materials, such as glass fiber tape, aramid tape, steel wire tape, etc.",
      "One step or two step production for option.",
    ],
    specHeaders: ["Model", "Pipe Range (mm)", "Line Speed (m/min)"],
    specs: [
      ["RTP250", "50 - 250", "0.8 - 3.0"],
      ["RTP315", "110 - 315", "0.5 - 2.5"],
      ["RTP630", "250 - 630", "0.2 - 1.5"],
    ],
  },
  "automatic-pipe-drilling-slotting-machine": {
    title: "Automatic Pipe Drilling/Slotting Machine",
    description: "Automatic pipe drilling and slotting machine for Ø 50-630mm pipes.",
    paragraphs: [
      "Our pipe drilling/slotting machine can produce pipe size range from Ø50-630mm.",
      "The machine can drill or slot on pipe surface fully automatically.",
      "The pipe are mainly used for water well, water pollution remove, water collection and filtration.",
      "The whole machine is controlled by PLC and servo control system, with high automation, stable and reliable, lower power consumption, suitable for different pipe diameter and length.",
    ],
    images: [
      "/images/products/automatic-pipe-drilling-slotting-machine/automatic-pipe-drilling-slotting-machine-hero.jpg",
      "/images/products/automatic-pipe-drilling-slotting-machine/automatic-pipe-drilling-machine-overview.jpg",
      "/images/products/automatic-pipe-drilling-slotting-machine/automatic-pipe-drilling-machine-operating-interface.png",
      "/images/products/automatic-pipe-drilling-slotting-machine/pipe-slotting-machine-cutting-station.jpg",
    ],
    videoId: "vKniztDXRLU",
    features: [
      "Parameters are directly input into the touch screen and the working steps are completed by the machine itself.",
      "Equip with double cutting stations, can increase production speed dramatically.",
      "Cutting station is well designed, and the sawdust falls directly into the collection box and is collected by the swarf extraction device.",
      "Quick pipe diameter and cutting blade changeover.",
    ],
    specHeaders: ["Model", "Pipe Diameter Range (mm)", "Pipe Length (m)", "Number of drill/saw", "Remark"],
    specs: [
      ["XRJ160", "50 - 160", "Customize according to requirement", "Customize according to requirement", "Can drill holes, making horizontal or vertical grooves according to requirement"],
      ["XRJ250", "75 - 250", "Customize according to requirement", "Customize according to requirement", "Can drill holes, making horizontal or vertical grooves according to requirement"],
      ["XRJ400", "160 - 400", "Customize according to requirement", "Customize according to requirement", "Can drill holes, making horizontal or vertical grooves according to requirement"],
      ["XRJ630", "250 - 630", "Customize according to requirement", "Customize according to requirement", "Can drill holes, making horizontal or vertical grooves according to requirement"],
    ],
  },
};

export function getProduct(slug) {
  return products[slug] || null;
}

export function getProductSlugs() {
  return Object.keys(products);
}
